syntax = "proto3";
package payment;
option go_package = "cinema/payment-service/proto/payment";

service PaymentService {
  rpc CreatePayment(CreatePaymentRequest) returns (PaymentResponse);
  rpc GetPayment(GetPaymentRequest) returns (PaymentResponse);
  rpc ListUserPayments(ListUserPaymentsRequest) returns (ListPaymentsResponse);
  rpc GetReceipt(GetReceiptRequest) returns (ReceiptResponse);
}

message Payment {
  string id = 1;
  string booking_id = 2;
  string user_id = 3;
  double amount = 4;
  string status = 5;
  string method = 6;
  string paid_at = 7;
}

message CreatePaymentRequest {
  string booking_id = 1;
  string user_id = 2;
  double amount = 3;
  string method = 4;
}
message GetPaymentRequest { string payment_id = 1; }
message ListUserPaymentsRequest { string user_id = 1; }
message GetReceiptRequest { string payment_id = 1; }

message PaymentResponse { Payment payment = 1; }
message ListPaymentsResponse { repeated Payment payments = 1; }
message ReceiptResponse {
  string payment_id = 1;
  string booking_id = 2;
  string user_email = 3;
  double amount = 4;
  string paid_at = 5;
  string movie_title = 6;
  string showtime = 7;
  repeated string seats = 8;
}
